### ISSUE TITLE
VHDL syntax validation

### ISSUE THREAD

**Issue by lenigoor** [Remillard/VHDL-Mode#104]
First I would like to express my thanks for making this plugin. While writing some VHDL code I found that the following snippet is incorrectly highlighted. Maybe this can be fixed?

![image](https://user-images.githubusercontent.com/9082936/44648266-cf456480-a9e0-11e8-9fe7-f404233a5c5b.png)

**Comment by Sv3n** [comment]
The match rule on https://github.com/Remillard/VHDL-Mode/blob/master/Syntax/VHDL.sublime-syntax#L1944 is too broad: it eats the opening bracket as the non-word character before the tick char, preventing the basic-paren-group from matching properly:

```yaml
  character-literal:
    # Any of the printable characters in the standard character set can be
    # used.  Used the non-word character element to protect against
    # single quote used for attributes (e.g. a'range)
    - match: '[^a-zA-Z0-9]('')'
```

A possible fix:

```yaml
  character-literal:
    # Any of the printable characters in the standard character set can be
    # used.  Used the non-word character element to protect against
    # single quote used for attributes (e.g. a'range)
    - match: '[^a-zA-Z0-9\(\)]('')'
```

(I was staring at a similar issue coincidentally)
